#!/bin/bash
ID=${AWS_ACCESS_KEY_ID:-$1}
SECRET_KEY=${AWS_SECRET_ACCESS_KEY:-$2}
SESSION_TOKEN=${AWS_SESSION_TOKEN:-$3}

sed -i 's|aws_access_key_id =.*|aws_access_key_id = '"$ID"'|' ~/.aws/credentials
sed -i 's|aws_secret_access_key =.*|aws_secret_access_key = '"$SECRET_KEY"'|' ~/.aws/credentials
sed -i 's|aws_session_token =.*|aws_session_token = '"$SESSION_TOKEN"'|' ~/.aws/credentials
