#!/bin/sh

session="${1:-dev}"
echo "Creating session $session"
# send-keys ' ls' \; \
# send-keys ' ll' \; \
# send-keys ':vsplit' C-m \; \

# session="${session:-dev}"
tmux new-session -s $session \; \
   send-keys 'cd ~/code/mily/backend && vim' C-m \; \
   send-keys ' ls' \; \
   send-keys ' ll' \; \
   send-keys ':vsplit' C-m \; \
   new-window \; \
   split-window -h \; \
   send-keys 'cd ~/code/' C-m \; \
   select-pane -t1 \; \
   send-keys 'cd ~/code/' C-m \; \
   select-window -t1 \; \
   select-pane -t1 \; \
