#!/bin/bash

DIR=/etc/apt/sources.list.d
SOURCES=/etc/apt/sources.list

if ! test -f "$DIR/vintela.list.bak"; then
  echo vintela.list.bak not found
  exit 1
fi

if ! test -f "$DIR/dl.google.com.list.bak"; then
  echo dl.google.com.list.bak not found
  exit 1
fi

if ! test -f "$SOURCES.aid.bak"; then
  echo $SOURCES.aid.bak not found
  exit 1
fi

sudo mv $DIR/dl.google.com.list.bak $DIR/dl.google.com.list
sudo cp "$SOURCES.aid.bak" $SOURCES
sudo mv $DIR/vintela.list.bak $DIR/vintela.list

sudo apt update
